### ISSUE TITLE
Add Nginx cache feature!  

### ISSUE THREAD

**Issue by dipakparmar** [dipakparmar/wordpress-git#5]
**Is your feature request related to a problem? Please describe.**
Using caching can improve server performance! 

**Describe the solution you'd like**
Include the fastcgi-nginx cache to have caching functionality in this docker image!  Also, cache purge should work with WordPress plugins like https://en-ca.wordpress.org/plugins/nginx-helper/

**Describe alternatives you've considered**
No alternative, the image can be available with two versions with caching functionality or without! 

**Additional context**
Follow this tutorial if you're new to Nginx and Docker: https://easyengine.io/wordpress-nginx/tutorials/single-site/fastcgi-cache-with-purging/

**Comment by cnp96** [comment]
@dipakparmar Can you please elaborate on the requirements?

**Comment by dipakparmar** [comment]
Hey @cnp96, thanks! I have updated the description for you.  

Let me know if you want to work on this so I can assign this issue to you. 😀
